"""create mapping tables

Revision ID: 8025b68a156e
Revises:
Create Date: 2026-09-04 19:42:40.227106

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8025b68a156e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epic_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("taiga_epic_id", sa.Integer(), nullable=False),
        sa.Column("kimai_project_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_epic_mappings")),
    )
    with op.batch_alter_table("epic_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_epic_mappings_kimai_project_id"),
            ["kimai_project_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_epic_mappings_taiga_epic_id"), ["taiga_epic_id"], unique=True
        )

    op.create_table(
        "project_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("taiga_project_id", sa.Integer(), nullable=False),
        sa.Column("kimai_customer_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_mappings")),
    )
    with op.batch_alter_table("project_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_mappings_kimai_customer_id"),
            ["kimai_customer_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_project_mappings_taiga_project_id"),
            ["taiga_project_id"],
            unique=True,
        )

    op.create_table(
        "task_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("taiga_task_id", sa.Integer(), nullable=False),
        sa.Column("kimai_activity_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_mappings")),
    )
    with op.batch_alter_table("task_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_mappings_kimai_activity_id"),
            ["kimai_activity_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_task_mappings_taiga_task_id"), ["taiga_task_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_mappings_taiga_task_id"))
        batch_op.drop_index(batch_op.f("ix_task_mappings_kimai_activity_id"))

    op.drop_table("task_mappings")
    with op.batch_alter_table("project_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_mappings_taiga_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_mappings_kimai_customer_id"))

    op.drop_table("project_mappings")
    with op.batch_alter_table("epic_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_epic_mappings_taiga_epic_id"))
        batch_op.drop_index(batch_op.f("ix_epic_mappings_kimai_project_id"))

    op.drop_table("epic_mappings")
    # ### end Alembic commands ###
